### ISSUE TITLE
'Resource not found' Errors when running terraform plan

### ISSUE THREAD

**Issue by timothymeyers** [azurenoops/ref-scca-enclave-starter#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Running `terraform plan -var-file=parameters.tfvars` results in two subnets in `06-shared-services/data.tf` not being found. I have not been able to track down a workaround or fix for it.

Both appear to be hardcoded in `data.tf` (see below).

<img width="401" alt="image" src="https://github.com/azurenoops/ref-scca-enclave-starter/assets/5417850/4d2880c4-3de5-4bd1-bb09-116d2a8f7251">

### Any log messages given by the failure

<img width="999" alt="image" src="https://github.com/azurenoops/ref-scca-enclave-starter/assets/5417850/d2f2742a-d37e-4b6d-8bec-98079a480d45">

### Expected/desired behavior

I would expect (1) the subnet names to be generated by `terraform plan` and (2) to follow the naming convention applied elsewhere.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by timothymeyers** [comment]
I am a little confused by a `terraform plan` complaining about resources not found when I would expect it should know about the dependencies on resources known only after apply?

**Comment by jrspinella** [comment]
This was added #19 to add dependency to the landing zone, to stop planning errors.
