### ISSUE TITLE
parameters.tfvars file is referenced in docs but is not in repository

### ISSUE THREAD

**Issue by timothymeyers** [azurenoops/ref-scca-enclave-starter#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Many of the steps in the `docs/` folder reference and link to a `parameters.tfvars` file that does not exist ([example](https://github.com/azurenoops/ref-scca-enclave-starter/blob/main/docs/00-Remote-State-Storage.md#configure-variables-for-state-management)).
`.gitignore` is configured to ignore *.tfvars files, which makes sense and explains why it would be missing in the repository.

Suggest a `parameters.tfvars.template` file be created with sane defaults and placeholder values that Consumers would need to update. This template file should live in the right place and Consumers should be given instructions to update it and then rename it to take off the .template extension.

And, `.gitignore` would not ignore it.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jrspinella** [comment]
See #19  I have updated the gitIgnore to add tfvars to the example as this is needed to run the example.
